# Generated by Django 5.0.3 on 2024-03-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstertype',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/Monsters/'),
        ),
    ]
